Fix missing a8m.phoneUS in angular.filter
'phoneUS' filter was not included into main 'angular.filter' module which causes injection error when entire 'angular.filter' module is included into project. As a result 'phoneUS' does not work as expected.

Console log:
Error: [$injector:unpr] Unknown provider: phoneUSFilterProvider <- phoneUSFilter